    name: TeleportSign
    main: sladki.tpsign.Teleport
    version: 1.01
    permissions:
        teleport.sign.create:
            default: op
    commands:
        teleportreloadconfig:    
            description: Reloads config of TeleportSign
            usage: /<command>           